version: "3"
services:
  postgre:
    container_name: postgresql
    image: postgres:12.17
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - C:\Users\HxTos\Documents\Git\Docker\DevopsPro\Docker_compose\bind_mount\postgre_vol:/var/lib/postgresql/data